### ISSUE TITLE
Changing Agent Collision Layer does not trigger enter/exit signals

### ISSUE THREAD

**Issue by zaknafean** [Arzzzen105/AreaOfSight2D#1]
In a project I'm playing with, the collision layer of the AreaOfSightAgent2D can change suddenly, like with a 'disguise' being removed or something along those lines. The attached video demonstrates the issue. Turning on my 'red' mode doesn't cause a 'collision' to occur

https://github.com/Arzzzen105/AreaOfVision2D/assets/7741797/9e0ac50d-c26f-4566-8d5d-8bfbf5731866

Godot 4.2
AreaOfVIsion2D 1.0

**Comment by Arzzzen105** [comment]
Hello! I'm not sure why this is happening. Can you provide properties of AOS and AOSAgent you set? Do you change some properties in the code?

**Comment by Arzzzen105** [comment]
Oh, I didn't get what you wanted to say. I guess adding setter for collision layer for agent can fix it. For now you can try to change "monitorable" property for agent to make Agent invisible. I will fix layers soon.

**Comment by zaknafean** [comment]
Changing monitorable defintiely lets me 'appear' to them when 'revealed'. But going hidden still doesn't' appear to trigger the 'exited' signal

https://github.com/Arzzzen105/AreaOfVision2D/assets/7741797/0b9a2e78-c553-4da5-95c4-2bd04345d550

**Comment by Arzzzen105** [comment]
Hey! I think I've managed to fix this issue. I'll make a commit in a few minutes. Take a look at the video:

https://github.com/Arzzzen105/AreaOfVision2D/assets/61621393/ae1ac46c-0276-4af8-931d-6f2a5b065bfd

The player goes invisible and becomes a bit transparent.

**Comment by Arzzzen105** [comment]
Done. I've just pushed a modification. Please, let me know if it helps!

**Comment by zaknafean** [comment]
Perfection! I can now add my 'feign death' and 'disguise' mechanics with great ease~! Thanks for making this awesome plugin. Can definitely close this issue up.

https://github.com/Arzzzen105/AreaOfSight2D/assets/7741797/64b08156-78e4-4262-99fc-4141c1dfa839

**Comment by Arzzzen105** [comment]
Thanks for using my first plugin :) Good luck
